"""
services/style_trend_registry.py
Deterministic source-backed registry for AHVI Trend Intelligence V1.

Schema, provenance concept, and freshness-window fields are adapted from
PR #48 (feat/trend-intelligence-dynamic, f0a57eb). The original 12 PR48
records (ORIGINAL_DISABLED_TRENDS below) remain in this file, permanently
disabled, as an audit trail -- see their per-record verification_status/
verification_note for why each failed (10/12 dead links, 2/12 unconfirmed
content; checked 2026-08-26). None of the original 12 were reusable.

PHASE 2 (2026-08-26): 7 new records (VERIFIED_TRENDS below) were sourced
and independently verified from scratch via live web search + fetch against
first-party editorial publications -- not AI trend summaries, SEO scraper
sites, Pinterest, blogs, or search-snippets-alone. Each record's
`verification_note` states exactly what was confirmed (URL resolves,
publisher, live title, byline, publication date) and the source excerpt the
keywords/colors/categories were drawn from. `verified_at` is the actual date
this verification was performed, not backdated. 6 of 7 are GLOBAL scope
(two publishers, both fall/winter-2026 season coverage); 1 is INDIA scope,
sourced from real India Couture Week 2026 runway coverage -- stored
narrowly (wedding/festive-occasion, couture-context) rather than
generalized into a claim about everyday Indian fashion the source doesn't
support.

TrendContextService.is_trend_valid() hard-gates on review_state=="approved"
AND verification_status=="VERIFIED" AND a parseable, non-future, in-window
verified_at -- so only the 7 VERIFIED_TRENDS records below are reachable at
runtime; the 12 disabled ones remain permanently inert.
"""
from typing import Any, Dict, List

ORIGINAL_DISABLED_TRENDS: List[Dict[str, Any]] = [
    {
        "trend_id": "relaxed_tailoring_2026",
        "label": "Relaxed Tailoring",
        "scope": "global",
        "region": ["global"],
        "gender": ["male", "female", "unisex"],
        "categories": ["top", "bottom", "outerwear", "shoes"],
        "colors": ["brown", "olive", "cream", "navy", "grey", "beige", "black"],
        "keywords": [
            "wide leg", "relaxed trouser", "trouser", "pleated",
            "overshirt", "unstructured blazer", "blazer",
            "oxford shirt", "tailored", "loafer",
        ],
        "occasions": ["office", "workwear", "smart_casual", "dinner", "weekend"],
        "season": ["spring", "summer", "monsoon", "autumn", "winter"],
        "strength": 0.85,
        "confidence": 0.88,
        "review_state": "unverified",
        "verification_status": "UNCONFIRMED_CONTENT",
        "verification_note": "URL resolves (HTTP 200) but live title is 'The Key Summer 2026 Trends...' -- topic/season mismatch with this record's claims.",
        "valid_from": "2026-01-01",
        "valid_until": "2026-12-31",
        "ingested_at": "2026-01-10T08:00:00Z",
        "verified_at": None,
        "source": {
            "publisher": "Vogue Fashion Index",
            "url": "https://www.vogue.com/article/spring-2026-fashion-trends",
            "published_at": "2026-01-15T00:00:00Z",
        },
    },
    {
        "trend_id": "earthy_neutrals_2026",
        "label": "Earthy Neutrals",
        "scope": "global",
        "region": ["global"],
        "gender": ["male", "female", "unisex"],
        "categories": ["top", "bottom", "outerwear", "shoes", "accessories"],
        "colors": ["olive", "khaki", "taupe", "tan", "sand", "brown", "beige", "cream", "rust"],
        "keywords": ["linen", "cotton", "overshirt", "chino", "knit", "earthy", "relaxed"],
        "occasions": ["casual", "smart_casual", "weekend", "travel", "brunch"],
        "season": ["spring", "summer", "monsoon", "autumn"],
        "strength": 0.80,
        "confidence": 0.84,
        "review_state": "unverified",
        "verification_status": "UNCONFIRMED_CONTENT",
        "verification_note": "Claimed URL used a placeholder numeric ID (a60000000) that the publisher's CMS silently redirected elsewhere -- redirect target's actual content was not confirmed.",
        "valid_from": "2026-01-01",
        "valid_until": "2026-12-31",
        "ingested_at": "2026-01-10T08:00:00Z",
        "verified_at": None,
        "source": {
            "publisher": "Harper's Bazaar Style Report",
            "url": "https://www.harpersbazaar.com/fashion/trends/a60000000/spring-2026-fashion-trends/",
            "published_at": "2026-01-20T00:00:00Z",
        },
    },
    {
        "trend_id": "elevated_basics_2026",
        "label": "Elevated Basics",
        "scope": "global",
        "region": ["global"],
        "gender": ["male", "female", "unisex"],
        "categories": ["top", "bottom", "shoes"],
        "colors": ["white", "black", "grey", "navy", "cream", "beige"],
        "keywords": ["heavyweight tee", "clean sneaker", "minimal sneaker", "fitted tee", "crisp shirt", "clean denim", "straight fit"],
        "occasions": ["casual", "smart_casual", "weekend", "workwear"],
        "season": ["spring", "summer", "autumn", "winter"],
        "strength": 0.75,
        "confidence": 0.82,
        "review_state": "unverified",
        "verification_status": "DEAD_LINK",
        "verification_note": "HTTP 404 on the claimed source URL (checked 2026-08-26).",
        "valid_from": "2026-01-01",
        "valid_until": "2026-12-31",
        "ingested_at": "2026-01-12T08:00:00Z",
        "verified_at": None,
        "source": {
            "publisher": "GQ Menswear Essentials",
            "url": "https://www.gq.com/story/mens-fashion-trends-2026",
            "published_at": "2026-01-10T00:00:00Z",
        },
    },
    {
        "trend_id": "deep_chocolate_2026",
        "label": "Chocolate & Deep Brown",
        "scope": "global",
        "region": ["global"],
        "gender": ["male", "female", "unisex"],
        "categories": ["top", "bottom", "outerwear", "shoes", "bags"],
        "colors": ["brown", "chocolate", "espresso", "mocha", "coffee"],
        "keywords": ["leather", "suede", "knit", "jacket", "cardigan", "boot", "loafer"],
        "occasions": ["smart_casual", "dinner", "evening", "autumn_winter"],
        "season": ["autumn", "winter", "monsoon"],
        "strength": 0.80,
        "confidence": 0.85,
        "review_state": "unverified",
        "verification_status": "DEAD_LINK",
        "verification_note": "HTTP 404 on the claimed source URL (checked 2026-08-26).",
        "valid_from": "2026-01-01",
        "valid_until": "2026-12-31",
        "ingested_at": "2026-01-11T08:00:00Z",
        "verified_at": None,
        "source": {
            "publisher": "ELLE Palette Intelligence",
            "url": "https://www.elle.com/fashion/trend-reports/a60000000/fashion-trends-2026/",
            "published_at": "2026-01-12T00:00:00Z",
        },
    },
    {
        "trend_id": "soft_utility_2026",
        "label": "Soft Utility",
        "scope": "global",
        "region": ["global"],
        "gender": ["male", "female", "unisex"],
        "categories": ["top", "bottom", "outerwear"],
        "colors": ["olive", "sage", "khaki", "navy", "black", "stone"],
        "keywords": ["cargo", "overshirt", "utility vest", "field jacket", "drawstring", "relaxed trouser"],
        "occasions": ["casual", "weekend", "travel", "outdoor"],
        "season": ["spring", "monsoon", "autumn"],
        "strength": 0.75,
        "confidence": 0.80,
        "review_state": "unverified",
        "verification_status": "DEAD_LINK",
        "verification_note": "HTTP 404 on the claimed source URL (checked 2026-08-26).",
        "valid_from": "2026-01-01",
        "valid_until": "2026-12-31",
        "ingested_at": "2026-01-14T08:00:00Z",
        "verified_at": None,
        "source": {
            "publisher": "WWD Trend Tracker",
            "url": "https://wwd.com/fashion-news/fashion-scoops/utility-fashion-trends-2026",
            "published_at": "2026-01-14T00:00:00Z",
        },
    },
    {
        "trend_id": "tonal_dressing_2026",
        "label": "Tonal Dressing",
        "scope": "global",
        "region": ["global"],
        "gender": ["male", "female", "unisex"],
        "categories": ["top", "bottom", "outerwear"],
        "colors": ["monochrome", "cream", "white", "beige", "grey", "navy", "black"],
        "keywords": ["monochrome", "tonal", "co-ord", "matching set", "knit set"],
        "occasions": ["casual", "smart_casual", "brunch", "dinner"],
        "season": ["spring", "summer", "autumn", "winter"],
        "strength": 0.70,
        "confidence": 0.78,
        "review_state": "unverified",
        "verification_status": "DEAD_LINK",
        "verification_note": "HTTP 404 on the claimed source URL (checked 2026-08-26).",
        "valid_from": "2026-01-01",
        "valid_until": "2026-12-31",
        "ingested_at": "2026-01-13T08:00:00Z",
        "verified_at": None,
        "source": {
            "publisher": "Refinery29 Style Direction",
            "url": "https://www.refinery29.com/en-us/monochrome-tonal-trends-2026",
            "published_at": "2026-01-11T00:00:00Z",
        },
    },
    {
        "trend_id": "relaxed_denim_2026",
        "label": "Relaxed Denim",
        "scope": "global",
        "region": ["global"],
        "gender": ["male", "female", "unisex"],
        "categories": ["bottom", "outerwear"],
        "colors": ["blue", "light blue", "dark blue", "black", "ecru"],
        "keywords": ["straight leg", "relaxed denim", "wide leg jeans", "denim jacket", "selvedge"],
        "occasions": ["casual", "weekend", "college", "travel"],
        "season": ["spring", "summer", "monsoon", "autumn", "winter"],
        "strength": 0.75,
        "confidence": 0.81,
        "review_state": "unverified",
        "verification_status": "DEAD_LINK",
        "verification_note": "HTTP 404 on the claimed source URL (checked 2026-08-26).",
        "valid_from": "2026-01-01",
        "valid_until": "2026-12-31",
        "ingested_at": "2026-01-15T08:00:00Z",
        "verified_at": None,
        "source": {
            "publisher": "Vogue Denim Review",
            "url": "https://www.vogue.com/article/best-denim-jeans-trends-2026",
            "published_at": "2026-01-14T00:00:00Z",
        },
    },
    {
        "trend_id": "textured_layers_2026",
        "label": "Textured Layers",
        "scope": "global",
        "region": ["global"],
        "gender": ["male", "female", "unisex"],
        "categories": ["top", "outerwear"],
        "colors": ["cream", "beige", "brown", "grey", "olive"],
        "keywords": ["waffle", "ribbed", "crochet", "boucle", "linen blend", "knit", "cardigan"],
        "occasions": ["casual", "smart_casual", "weekend", "brunch"],
        "season": ["spring", "monsoon", "autumn"],
        "strength": 0.70,
        "confidence": 0.76,
        "review_state": "unverified",
        "verification_status": "DEAD_LINK",
        "verification_note": "HTTP 404 on the claimed source URL (checked 2026-08-26).",
        "valid_from": "2026-01-01",
        "valid_until": "2026-12-31",
        "ingested_at": "2026-01-15T08:00:00Z",
        "verified_at": None,
        "source": {
            "publisher": "Marie Claire Layering Guide",
            "url": "https://www.marieclaire.com/fashion/knitwear-layering-trends-2026/",
            "published_at": "2026-01-13T00:00:00Z",
        },
    },
    {
        "trend_id": "minimal_monochrome_2026",
        "label": "Minimal Monochrome",
        "scope": "global",
        "region": ["global"],
        "gender": ["male", "female", "unisex"],
        "categories": ["top", "bottom", "shoes"],
        "colors": ["black", "white", "charcoal", "grey"],
        "keywords": ["clean lines", "minimal", "structured tee", "tailored pant", "chelsea boot", "minimal sneaker"],
        "occasions": ["office", "smart_casual", "dinner", "night_out"],
        "season": ["spring", "summer", "autumn", "winter"],
        "strength": 0.80,
        "confidence": 0.86,
        "review_state": "unverified",
        "verification_status": "DEAD_LINK",
        "verification_note": "HTTP 404 on the claimed source URL (checked 2026-08-26).",
        "valid_from": "2026-01-01",
        "valid_until": "2026-12-31",
        "ingested_at": "2026-01-12T08:00:00Z",
        "verified_at": None,
        "source": {
            "publisher": "GQ Minimalist Edit",
            "url": "https://www.gq.com/story/minimal-fashion-guide-2026",
            "published_at": "2026-01-10T00:00:00Z",
        },
    },
    {
        "trend_id": "modern_ethnic_2026",
        "label": "Contemporary Indian",
        "scope": "india",
        "region": ["india"],
        "gender": ["male", "female", "unisex"],
        "categories": ["top", "bottom", "ethnic_wear"],
        "colors": ["cream", "mustard", "maroon", "indigo", "terracotta", "white"],
        "keywords": ["short kurta", "linen kurta", "nehru jacket", "bandhgala", "indie fusion", "cotton tunic"],
        "occasions": ["festive", "family_event", "puja", "smart_casual", "wedding_guest"],
        "season": ["spring", "summer", "monsoon", "autumn", "winter"],
        "strength": 0.85,
        "confidence": 0.89,
        "review_state": "unverified",
        "verification_status": "DEAD_LINK",
        "verification_note": "HTTP 404 on the claimed source URL (checked 2026-08-26).",
        "valid_from": "2026-01-01",
        "valid_until": "2026-12-31",
        "ingested_at": "2026-01-10T08:00:00Z",
        "verified_at": None,
        "source": {
            "publisher": "Vogue India Festive Report",
            "url": "https://www.vogue.in/fashion/content/indian-festive-ethnic-wear-trends-2026",
            "published_at": "2026-01-18T00:00:00Z",
        },
    },
    {
        "trend_id": "festive_jewel_tones_2026",
        "label": "Festive Jewel Tones",
        "scope": "india",
        "region": ["india"],
        "gender": ["male", "female", "unisex"],
        "categories": ["top", "bottom", "ethnic_wear", "dresses"],
        "colors": ["emerald", "ruby", "sapphire", "plum", "teal", "deep gold", "burgundy"],
        "keywords": ["silk", "brocade", "embroidery", "festive kurta", "sherwani", "lehenga", "anarkali"],
        "occasions": ["wedding", "festive", "reception", "diwali", "sangeet"],
        "season": ["autumn", "winter"],
        "strength": 0.90,
        "confidence": 0.92,
        "review_state": "unverified",
        "verification_status": "DEAD_LINK",
        "verification_note": "HTTP 404 on the claimed source URL (checked 2026-08-26).",
        "valid_from": "2026-01-01",
        "valid_until": "2026-12-31",
        "ingested_at": "2026-01-09T08:00:00Z",
        "verified_at": None,
        "source": {
            "publisher": "Harper's Bazaar India Wedding Issue",
            "url": "https://www.harpersbazaar.in/fashion/jewel-tone-wedding-trends-2026",
            "published_at": "2026-01-07T00:00:00Z",
        },
    },
    {
        "trend_id": "statement_accessories_2026",
        "label": "Statement Accents",
        "scope": "global",
        "region": ["global"],
        "gender": ["male", "female", "unisex"],
        "categories": ["accessories", "jewelry", "bags", "footwear"],
        "colors": ["silver", "gold", "tan", "black", "metallic"],
        "keywords": ["chunky loafer", "leather tote", "silver chain", "minimal watch", "structured bag"],
        "occasions": ["smart_casual", "dinner", "office", "weekend"],
        "season": ["spring", "summer", "autumn", "winter"],
        "strength": 0.65,
        "confidence": 0.75,
        "review_state": "unverified",
        "verification_status": "DEAD_LINK",
        "verification_note": "HTTP 404 on the claimed source URL (checked 2026-08-26).",
        "valid_from": "2026-01-01",
        "valid_until": "2026-12-31",
        "ingested_at": "2026-01-14T08:00:00Z",
        "verified_at": None,
        "source": {
            "publisher": "Elle Accessory Tracker",
            "url": "https://www.elle.com/fashion/accessories/statement-accents-2026",
            "published_at": "2026-01-12T00:00:00Z",
        },
    },
]


# ---------------------------------------------------------------------------
# Phase 2: independently re-sourced and verified 2026-08-26. Each record's
# keywords/colors/categories are drawn only from what the fetched article
# excerpt actually stated -- fields the source didn't specify are left empty
# rather than invented. occasions use ONLY the confirmed literal output
# vocabulary of brain.engines.style_scorer.normalize_occasion() (beach,
# brunch, capsule, casual, cocktail, date_night, office, party, travel,
# wedding, workout) -- not "evening"/"festive"/"dinner", which that function
# never actually returns, so a trend using those words would silently never
# match at runtime.
# ---------------------------------------------------------------------------
VERIFIED_TRENDS: List[Dict[str, Any]] = [
    {
        "trend_id": "modern_heirlooms_2026",
        "label": "Modern Heirlooms",
        "scope": "global",
        "region": ["global"],
        "gender": ["male", "female", "unisex"],
        "categories": ["outerwear", "dresses", "jewelry"],
        "colors": [],
        "keywords": ["brocade", "jacquard", "embroidery", "beaded", "embellished coat", "gown", "estate jewelry"],
        "occasions": ["cocktail", "wedding", "party"],
        "season": ["autumn", "winter"],
        "strength": 0.6,
        "confidence": 0.65,
        "review_state": "approved",
        "verification_status": "VERIFIED",
        "verification_note": "Fetched live 2026-08-26. Title matches exactly: '10 Fashion Month Trends Set to Define Fall/Winter 2026 Style | Who What Wear'. Byline Kristen Nichols and Eliza Huber. 'Modern Heirlooms' section confirmed: rich brocade/jacquard fabrics, intricate embroidery, beaded details, embellished coats, sophisticated gowns, estate jewelry.",
        "valid_from": "2026-07-28",
        "valid_until": "2027-01-31",
        "ingested_at": "2026-08-26T00:00:00Z",
        "verified_at": "2026-08-26T00:00:00Z",
        "source": {
            "publisher": "Who What Wear",
            "url": "https://www.whowhatwear.com/fashion/runway/fashion-week-trends-fall-winter-2026",
            "published_at": "2026-07-28T00:00:00Z",
        },
    },
    {
        "trend_id": "office_hours_skirt_suits_2026",
        "label": "Office Hours (Skirt Suits)",
        "scope": "global",
        "region": ["global"],
        "gender": ["female", "unisex"],
        "categories": ["outerwear", "bottom"],
        "colors": [],
        "keywords": ["skirt suit", "blazer", "asymmetric hem", "houndstooth"],
        "occasions": ["office"],
        "season": ["autumn", "winter"],
        "strength": 0.6,
        "confidence": 0.65,
        "review_state": "approved",
        "verification_status": "VERIFIED",
        "verification_note": "Fetched live 2026-08-26. Title matches exactly: \"8 Fashion Trends We're Buying for Fall 2026 | Who What Wear\" republished/aggregated at coveteur.com by Ella O'Keeffe, published 2026-08-12. 'Office Hours' section confirmed: blazers, skirt suits, asymmetric hems, off-kilter button details, houndstooth patterns, professional/workwear context.",
        "valid_from": "2026-08-12",
        "valid_until": "2027-02-28",
        "ingested_at": "2026-08-26T00:00:00Z",
        "verified_at": "2026-08-26T00:00:00Z",
        "source": {
            "publisher": "Coveteur",
            "url": "https://coveteur.com/fall-fashion-trends-2026",
            "published_at": "2026-08-12T00:00:00Z",
        },
    },
    {
        "trend_id": "touch_point_texture_2026",
        "label": "Touch Point (Texture)",
        "scope": "global",
        "region": ["global"],
        "gender": ["male", "female", "unisex"],
        "categories": ["outerwear"],
        "colors": [],
        "keywords": ["fur coat", "shearling", "fringe", "pile fabric"],
        "occasions": ["casual", "travel"],
        "season": ["autumn", "winter"],
        "strength": 0.55,
        "confidence": 0.65,
        "review_state": "approved",
        "verification_status": "VERIFIED",
        "verification_note": "Same article as office_hours_skirt_suits_2026 (Coveteur, Ella O'Keeffe, 2026-08-12). 'Touch Point' section confirmed: fur coats, shearling jackets, pile fabrics, fringe accents.",
        "valid_from": "2026-08-12",
        "valid_until": "2027-02-28",
        "ingested_at": "2026-08-26T00:00:00Z",
        "verified_at": "2026-08-26T00:00:00Z",
        "source": {
            "publisher": "Coveteur",
            "url": "https://coveteur.com/fall-fashion-trends-2026",
            "published_at": "2026-08-12T00:00:00Z",
        },
    },
    {
        "trend_id": "night_moves_dark_romance_2026",
        "label": "Night Moves (Dark Romance)",
        "scope": "global",
        "region": ["global"],
        "gender": ["female", "unisex"],
        "categories": ["dresses", "top"],
        "colors": ["jewel tone", "burgundy"],
        "keywords": ["lace dress", "corsetry", "high neck", "feathered", "asymmetric hem"],
        "occasions": ["cocktail", "party", "date_night"],
        "season": ["autumn", "winter"],
        "strength": 0.6,
        "confidence": 0.65,
        "review_state": "approved",
        "verification_status": "VERIFIED",
        "verification_note": "Same article as office_hours_skirt_suits_2026 (Coveteur, Ella O'Keeffe, 2026-08-12). 'Night Moves' section confirmed: lace dresses, corsetry, high-neck pieces, feathered bolero shrugs, asymmetric hems, jewel tones, moody palettes, evening context.",
        "valid_from": "2026-08-12",
        "valid_until": "2027-01-31",
        "ingested_at": "2026-08-26T00:00:00Z",
        "verified_at": "2026-08-26T00:00:00Z",
        "source": {
            "publisher": "Coveteur",
            "url": "https://coveteur.com/fall-fashion-trends-2026",
            "published_at": "2026-08-12T00:00:00Z",
        },
    },
    {
        "trend_id": "shape_shift_proportion_2026",
        "label": "Shape Shift (Proportion Play)",
        "scope": "global",
        "region": ["global"],
        "gender": ["female", "unisex"],
        "categories": ["outerwear", "bottom"],
        "colors": [],
        "keywords": ["oversized shoulder", "peplum", "mini skirt", "dropped waist", "high-low"],
        "occasions": ["party", "cocktail"],
        "season": ["autumn", "winter"],
        "strength": 0.55,
        "confidence": 0.62,
        "review_state": "approved",
        "verification_status": "VERIFIED",
        "verification_note": "Same article as office_hours_skirt_suits_2026 (Coveteur, Ella O'Keeffe, 2026-08-12). 'Shape Shift' section confirmed: mini skirts with high-low trains, oversized shoulder pads, peplum details, ultra-dropped waists.",
        "valid_from": "2026-08-12",
        "valid_until": "2027-02-28",
        "ingested_at": "2026-08-26T00:00:00Z",
        "verified_at": "2026-08-26T00:00:00Z",
        "source": {
            "publisher": "Coveteur",
            "url": "https://coveteur.com/fall-fashion-trends-2026",
            "published_at": "2026-08-12T00:00:00Z",
        },
    },
    {
        "trend_id": "its_a_wrap_shrouds_2026",
        "label": "It's A Wrap (Shrouds)",
        "scope": "global",
        "region": ["global"],
        "gender": ["male", "female", "unisex"],
        "categories": ["outerwear"],
        "colors": [],
        "keywords": ["cape", "shroud", "structured knit"],
        "occasions": ["casual", "travel"],
        "season": ["autumn", "winter"],
        "strength": 0.55,
        "confidence": 0.62,
        "review_state": "approved",
        "verification_status": "VERIFIED",
        "verification_note": "Same article as office_hours_skirt_suits_2026 (Coveteur, Ella O'Keeffe, 2026-08-12). 'It's A Wrap' section confirmed: capes, shroud-like knitwear, structured tops keeping arms close to body, layering/outerwear context, check patterns mentioned.",
        "valid_from": "2026-08-12",
        "valid_until": "2027-02-28",
        "ingested_at": "2026-08-26T00:00:00Z",
        "verified_at": "2026-08-26T00:00:00Z",
        "source": {
            "publisher": "Coveteur",
            "url": "https://coveteur.com/fall-fashion-trends-2026",
            "published_at": "2026-08-12T00:00:00Z",
        },
    },
    {
        "trend_id": "india_couture_week_embellished_ethnic_2026",
        "label": "India Couture Week Embellished Ethnic",
        "scope": "india",
        "region": ["india"],
        "gender": ["female", "unisex"],
        "categories": ["ethnic_wear"],
        "colors": ["red", "gold", "wine", "ivory", "silver", "blue"],
        "keywords": ["lehenga", "sari", "saree", "zardozi", "mirror work", "bandhani", "embroidery", "corseted blouse"],
        "occasions": ["wedding", "party"],
        "season": ["autumn", "winter"],
        "strength": 0.65,
        "confidence": 0.75,
        "review_state": "approved",
        "verification_status": "VERIFIED",
        "verification_note": (
            "Fetched live 2026-08-26. Title/byline confirmed: 'India Couture Week 2026 in all its "
            "glory: Celebrating the artisans, the atelier, and the art of couture', Harper's Bazaar "
            "India, by Santya Ahuja, published 2026-07-30. Confirmed runway coverage across multiple "
            "designers: sculpted lehengas, fluid saris, corseted blouses, zardozi/bandhani/mirror-work "
            "embroidery, palette including deep reds, antique golds, wines, ivories, silvers, celestial "
            "blues. Stored narrowly as India Couture Week runway coverage (wedding/festive occasion "
            "context), NOT generalized into a claim about everyday Indian fashion -- the source is "
            "couture-week reporting, not a market-wide trend survey."
        ),
        "valid_from": "2026-07-30",
        "valid_until": "2027-02-28",
        "ingested_at": "2026-08-26T00:00:00Z",
        "verified_at": "2026-08-26T00:00:00Z",
        "source": {
            "publisher": "Harper's Bazaar India",
            "url": "https://www.harpersbazaar.in/fashion/story/india-couture-week-2026-in-all-its-glory-celebrating-the-artisans-the-atelier-and-the-art-of-couture-1431572-2026-07-30",
            "published_at": "2026-07-30T00:00:00Z",
        },
    },
]


def get_trend_registry() -> List[Dict[str, Any]]:
    """Return all curated trend records (verified and permanently-disabled
    alike). Callers must go through TrendContextService.is_trend_valid()/
    get_active_trends() -- this function does not filter by verification
    status itself, it is the raw registry.
    """
    return ORIGINAL_DISABLED_TRENDS + VERIFIED_TRENDS
